const MENU_WIDTH = 140

const CELL_SIZE = 65
const NUMBER_OF_CELLS_PER_ROW = 8
const BOARD_SIZE = NUMBER_OF_CELLS_PER_ROW * CELL_SIZE

export {
  BOARD_SIZE,
  CELL_SIZE,
  MENU_WIDTH,
  NUMBER_OF_CELLS_PER_ROW
}
